### ISSUE TITLE
Invalid class string

### ISSUE THREAD

**Issue by DevMinions** [huskar-t/opcae#1]
您好，在使用这个库远程访问ae服务器的时候会报“Invalid class string”这个错误，但是在本地就可以正常的连接到本地ae服务，是需要安装什么吗？感谢您的时间和帮助！

**Comment by huskar-t** [comment]
@yuminuo I updated the dependencies, you can try it with the commit
c40cb82

**Comment by DevMinions** [comment]
@huskar-t I tried it, but it still reports the same error. I used the AE simulated by Kepware.KEPServerEX_AE.V6 on the remote end.

**Comment by huskar-t** [comment]
@yuminuo try [f2e8918](https://github.com/huskar-t/opcae/commit/f2e89184e2625e0ebacdac64e9e87c039e58ac0c)

**Comment by DevMinions** [comment]
@huskar-t It worked. Thanks！！
